#!/bin/bash
set -ex # fail on first error, print commands

echo "Checking documentation..."
python -m pydocstyle coviz
echo "Success!"

echo "Checking code style with black..."
python -m black --line-length 90 --check coviz
echo "Success!"

echo "Checking code style with pylint..."
python -m pylint coviz
echo "Success!"

echo "Running unit tests..."
python -m pytest -v
echo "Success!"
